# Generated by Django 3.1.7 on 2021-03-30 08:19

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('phone_number', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Номер телефона')),
                ('first_name', models.CharField(max_length=256, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=256, verbose_name='Фамилия')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Почта')),
                ('company_name', models.CharField(max_length=256, verbose_name='Название компании')),
                ('region', models.CharField(max_length=256, verbose_name='Регион')),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('phone_number', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Номер телефона')),
                ('first_name', models.CharField(max_length=256, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=256, verbose_name='Фамилия')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Почта')),
                ('city', models.CharField(max_length=256, verbose_name='Город')),
            ],
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('info', models.TextField(help_text='Введите основную информацию')),
                ('profession', models.CharField(max_length=256, verbose_name='Искомая должность')),
                ('work_experience', models.BooleanField(default=False, verbose_name='Опыт работы')),
                ('education', models.TextField(blank=True, null=True, verbose_name='Образование')),
                ('languages', models.TextField(blank=True, null=True, verbose_name='Владение языками')),
                ('employers_phone', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hh.employer')),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('info', models.TextField(help_text='Введите основную информацию')),
                ('profession', models.CharField(max_length=256, verbose_name='Желаемая должность')),
                ('work_experience', models.BooleanField(default=False, verbose_name='Опыт работы')),
                ('education', models.CharField(max_length=256, verbose_name='Образование')),
                ('languages', models.CharField(max_length=256, verbose_name='Владение языками')),
                ('workers_phone', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hh.worker')),
            ],
        ),
    ]
