# Generated by Django 3.1.7 on 2021-04-27 19:39

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worker_cover', models.ImageField(default='images/user.png', upload_to='images/')),
                ('first_name', models.CharField(max_length=256, null=True, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=256, null=True, verbose_name='Фамилия')),
                ('phone_number', models.CharField(max_length=20, null=True, verbose_name='Мобильный телефон')),
                ('city', models.CharField(default='Москва', max_length=256, verbose_name='Город проживания')),
                ('info', models.TextField(help_text='Введите основную информацию', null=True)),
                ('profession', models.CharField(max_length=256, null=True, verbose_name='Желаемая должность')),
                ('work_experience', models.BooleanField(default=False, null=True, verbose_name='Опыт работы')),
                ('education', models.CharField(max_length=256, null=True, verbose_name='Образование')),
                ('languages', models.CharField(max_length=256, null=True, verbose_name='Владение языками')),
            ],
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=25, null=True, verbose_name='Наименование компании')),
                ('company_cover', models.ImageField(default='images/enterprise.png', upload_to='images/')),
                ('phone_number', models.CharField(max_length=20, null=True, verbose_name='Мобильный телефон')),
                ('info', models.TextField(help_text='Введите основную информацию', null=True)),
                ('profession', models.CharField(max_length=50, null=True, verbose_name='Искомая должность')),
                ('work_experience', models.BooleanField(default=False, null=True, verbose_name='Опыт работы')),
                ('education', models.TextField(blank=True, null=True, verbose_name='Образование')),
                ('languages', models.TextField(blank=True, null=True, verbose_name='Владение языками')),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('resumes', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hh.resume')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
                ('vacancies', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hh.vacancy')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
