# Generated by Django 3.1.7 on 2021-04-27 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hh', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='resumes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hh.resume'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='vacancies',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hh.vacancy'),
        ),
    ]
