# Generated by Django 3.1.7 on 2021-04-27 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hh', '0004_auto_20210428_0156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='worker_cover',
        ),
    ]
